export const entityNameMapping = {
	person: "People",
	norp: "Groups",
	fac: "Structures",
	organization: "Organizations",
	location: "Locations",
	places: "Places",
	product: "Products",
	event: "Events",
	art: "Art",
	law: "Law",
	language: "Languages",
	date: "Dates",
	time: "Times",
	percent: "Percentages",
	money: "Money",
	quantity: "Quantities",
	ordinal: "Ordinal Numbers",
	cardinal: "Cardinal Numbers",
}
